services:
  postgres:
    image: postgis/postgis:15-3.4
    platform: ${TARGETPLATFORM:-linux/amd64}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petbnb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3001"
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/app_db
      - NODE_ENV=development
      - PORT=3001
      - RUNNING_IN_DOCKER=true
    command: sh -c "./scripts/wait-for-it.sh postgres:5432 -- npm run migrate && npm run seed && npm run dev"

volumes:
  postgres_data: